receivers:
  otlp:
    protocols:
      grpc: # 4317 
      http: # 4318
  hostmetrics: #cpu metric
    collection_interval: 10s
    scrapers:
      cpu: { }
      memory: { }
      filesystem: { }
      network: { }
      disk: { }
      load: { }

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "otel-collector"


service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [prometheus]

#  jeager/kibana eklenirse açılır
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging]
#
#    logs:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging]
